### PR TITLE
Rename locust.py to locustfile.py 

### PR DESCRIPTION
**Pull request by JLHasson**
With the locust file named `locust.py` you hit the following error:
```
locust -f locust.py --headless --users 10 --spawn-rate 1 -H http://localhost:5002
Traceback (most recent call last):
  File "/.../venv/bin/locust", line 5, in <module>
    from locust.main import main
  File "/.../sample-fastAPI-app/locust.py", line 2, in <module>
    from locust import HttpUser, task, between
ImportError: cannot import name 'HttpUser' from partially initialized module 'locust' (most likely due to a circular im
port) (/.../sample-fastAPI-app/locust.py)
```

Renaming to `locustfile.py` fixes this issue.

### CODE REVIEW

**Comment by JLHasson** [comment]
Should also update the SigNoz documentation

**Comment by pranay01** [comment]
@srikanthccv can you check if this looks good?

**Comment by pranay01** [comment]
@JLHasson You can also update docs by raising a PR here - https://github.com/SigNoz/signoz.io

**Review by srikanthccv — APPROVED** [review]
Thanks @JLHasson . Would you mind updating the [README](https://github.com/SigNoz/sample-fastAPI-app#send-traffic)?

**Pull request merged**
